FROM redis:alpine
COPY ./redis.conf-template /
ARG LEADER_PASSWORD
ARG REPLICAOF 
RUN apk add gettext
RUN mkdir -p /usr/local/redis/
RUN chmod 777 /usr/local/redis/ 
RUN envsubst < /redis.conf-template > /usr/local/redis/redis-server.conf
RUN chmod 666 /usr/local/redis/redis-server.conf
RUN ls -l /usr/local/redis/redis-server.conf
RUN cat /usr/local/redis/redis-server.conf
EXPOSE 6379
